version: 0.2

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - sed -i "s/BUILD_VERSION_PLACEHOLDER/$COMMIT_HASH/g" src/app/components/footer/footer.component.html
      - npm install
      - $(npm bin)/ng build --prod
      - docker build -t $IMAGE_REPO/$MODULE_NAME:$COMMIT_HASH .
      - docker push $IMAGE_REPO/$MODULE_NAME:$COMMIT_HASH
